### ISSUE TITLE
Closing last tab enters browser into invalid state

### ISSUE THREAD

**Issue by Gozala** [browserhtml/browser.html#873]
Steps to reproduce:

1.  Type `foo` in location bar and hit enter.
2. Once page loads trigger `cmd w` keybinding.

Expected behavior:

See create tab view.

Actual behavior:

Tab does not get closed.

**Comment by Gozala** [comment]
I know it worked in #c62802288465ce3dcbcc7130c0930607bf90a214 & there were only handful of commits since which is where I expect it got regressed.

**Comment by Gozala** [comment]
e59ccb7bfa37b7a7240861dacf31fe2ca1f7d58e seem to have regressed going back to create-tab mode but works never the less.

**Comment by gordonbrander** [comment]
@Gozala this is working for me
